services:
  - type: web
    name: document-summarizer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

    build:
      packages:
        - poppler-utils     # For PDFs
        - tesseract-ocr     # Required for pytesseract
        - libgl1            # OpenCV
        - libglib2.0-0      # OpenCV GUI backend
